name: crawl
on:
  push
  # schedule:
  #   # “At 00:00 on Sunday.”
  #   - cron: '0 0 * * 0'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: request crawl
        run: curl -I -X GET https://osmrtnice.vercel.app/api/crawl
