name: crawl
on:
  schedule:
    # “At 00:00 on Sunday.”
    - cron: '0 0 * * 0'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: request crawl
      - run: curl -X GET https://osmrtnice-the-kwisatz-haderach.vercel.app/api/crawl
